sample_info_bucket: "pbc-qcarray-sample-info"
gtc_bucket: "pbc-iscan-qcarrays" 
JIRA: "JEWSC_20220425_QCarray"
manifest: "pbc-qcarray-batch-files/JEWSC_20220425_QCarray/iScan manifest_with subject IDs_220427.xlsx"
expected_pairings: ["pbc-qcarray-batch-files/JEWSC_20220425_QCarray/CPTAC iScan Expected Parings 4.27.2022.xlsx","pbc-qcarray-batch-files/JEWSC_20220425_QCarray/Moonshot Expected Pairings 4.27.2021.xlsx"]