AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: pbs-iscan-qcarray
Parameters:
  SampleDataBucket:
    Type: String
    Description: Name of the bucket containing *.idat and *.gtc files
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "(?!^(\\d{1,3}\\.){3}\\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\\.[a-z0-9])?)*$(?<!\\-))"
  BatchFilesBucket:
    Type: String
    Description: Name of the bucket containing the .xlsx and .csv batch metadata files
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "(?!^(\\d{1,3}\\.){3}\\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\\.[a-z0-9])?)*$(?<!\\-))"
  SampleInfoBucket:
    Type: String
    Description: Name of the bucket containing the .parquet files
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "(?!^(\\d{1,3}\\.){3}\\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\\.[a-z0-9])?)*$(?<!\\-))"
  ManifestFilename:
    Type: String
    Description: Name of the BeadChip manifest (.bpm) file

Globals:
  Function:
    Environment:
      Variables:
        DEBUG: 'False'

Resources:
  IaapCli:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./iaap-cli

  wranglerLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: 'arn:aws:serverlessrepo:us-east-1:336392948345:applications/aws-data-wrangler-layer-py3-9'
        SemanticVersion: 2.15.1

  gencallFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gencall/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 15
      MemorySize: 1536
      Architectures:
        - x86_64
      Environment:
        Variables:
          MANIFEST_CLUSTER_BUCKET: !Ref SampleDataBucket
      Layers:
      - !Ref IaapCli
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref SampleDataBucket
      - S3WritePolicy:
          BucketName: !Ref SampleDataBucket
      # Events:
      #   S3Event:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref SampleDataBucket
      #       Events: s3:ObjectCreated:*
      #       Filter:
      #         S3Key:
      #           Rules:
      #           - Name: suffix
      #             Value: _Red.idat

  sampleinfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sample-info/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 1536
      Architectures:
        - x86_64
      Environment:
        Variables:
          SAMPLE_INFO_BUCKET: !Ref SampleInfoBucket
      Layers:
      - !GetAtt wranglerLayer.Outputs.WranglerLayer39Arn
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref BatchFilesBucket
      - S3WritePolicy:
          BucketName: !Ref SampleInfoBucket
      # Events:
      #   S3Event:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref BatchFilesBucket
      #       Events: s3:ObjectCreated:*

  gtctableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gtc-table/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 1536
      Architectures:
        - x86_64
      Environment:
        Variables:
          MANIFEST_FILENAME: !Ref ManifestFilename
      Layers:
      - !GetAtt wranglerLayer.Outputs.WranglerLayer39Arn
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref SampleDataBucket
      - S3WritePolicy:
          BucketName: !Ref SampleDataBucket
      # Events:
      #   S3Event:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref BatchFilesBucket
      #       Events: s3:ObjectCreated:*

  gencallFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${gencallFunction}'
      RetentionInDays: 30
  
  sampleinfoFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${sampleinfoFunction}'
      RetentionInDays: 30