cluster: awsbatch-submit-job.py
default-resources:
  - runtime=1440
  - queue=getting-started-job-queue
  - job_definition=getting-started-job-definition
jobs: 150
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: mamba
cluster-status: awsbatch-describe-jobs.py
cluster-cancel: awsbatch-terminate-job.py
cluster-cancel-nargs: 1
max-status-checks-per-second: 0.5
default-remote-provider: S3
default-remote-prefix: pbc-iscan-qcarrays